//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/ErrorCodeDefine.proto
namespace protocol
{
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCodeDefine")]
    public enum ErrorCodeDefine
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_SUCCEED", Value=0)]
      LOGIN_SUCCEED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACCOUNT_EEROR", Value=1)]
      ACCOUNT_EEROR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PASSWORD_ERROR", Value=2)]
      PASSWORD_ERROR = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REGISTER_SUCCEED", Value=3)]
      REGISTER_SUCCEED = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACCOUNT_EXISTS", Value=4)]
      ACCOUNT_EXISTS = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HANDLE_SHAKE_FAILE", Value=5)]
      HANDLE_SHAKE_FAILE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HANDLE_SHAKE_SUCCEED", Value=6)]
      HANDLE_SHAKE_SUCCEED = 6
    }
  
}