//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/ProtoDefine.proto
namespace protocol
{
    [global::ProtoBuf.ProtoContract(Name=@"ProtoDefine")]
    public enum ProtoDefine
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Handshake", Value=0)]
      Handshake = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqLogin", Value=1)]
      ReqLogin = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReqRegister", Value=2)]
      ReqRegister = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RetLogin", Value=3)]
      RetLogin = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RetRegister", Value=4)]
      RetRegister = 4
    }
  
}