// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ErrorCodeDefine.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from ErrorCodeDefine.proto</summary>
  public static partial class ErrorCodeDefineReflection {

    #region Descriptor
    /// <summary>File descriptor for ErrorCodeDefine.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ErrorCodeDefineReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVFcnJvckNvZGVEZWZpbmUucHJvdG8SCHByb3RvY29sKqcBCg9FcnJvckNv",
            "ZGVEZWZpbmUSEQoNTE9HSU5fU1VDQ0VFRBAAEhEKDUFDQ09VTlRfRUVST1IQ",
            "ARISCg5QQVNTV09SRF9FUlJPUhACEhQKEFJFR0lTVEVSX1NVQ0NFRUQQAxIS",
            "Cg5BQ0NPVU5UX0VYSVNUUxAEEhYKEkhBTkRMRV9TSEFLRV9GQUlMRRAFEhgK",
            "FEhBTkRMRV9TSEFLRV9TVUNDRUVEEAY="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.ErrorCodeDefine), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ErrorCodeDefine {
    /// <summary>
    ///µ«¬º≥…π¶
    /// </summary>
    [pbr::OriginalName("LOGIN_SUCCEED")] LoginSucceed = 0,
    /// <summary>
    ///’À∫≈¥ÌŒÛ
    /// </summary>
    [pbr::OriginalName("ACCOUNT_EEROR")] AccountEeror = 1,
    /// <summary>
    ///√‹¬Î¥ÌŒÛ
    /// </summary>
    [pbr::OriginalName("PASSWORD_ERROR")] PasswordError = 2,
    /// <summary>
    ///◊¢≤·≥…π¶
    /// </summary>
    [pbr::OriginalName("REGISTER_SUCCEED")] RegisterSucceed = 3,
    /// <summary>
    ///’À∫≈“—¥Ê‘⁄
    /// </summary>
    [pbr::OriginalName("ACCOUNT_EXISTS")] AccountExists = 4,
    /// <summary>
    ///Œ’ ÷≥…π¶
    /// </summary>
    [pbr::OriginalName("HANDLE_SHAKE_FAILE")] HandleShakeFaile = 5,
    /// <summary>
    ///Œ’ ÷ ß∞‹
    /// </summary>
    [pbr::OriginalName("HANDLE_SHAKE_SUCCEED")] HandleShakeSucceed = 6,
  }

  #endregion

}

#endregion Designer generated code
